future: true
title: NaroZeol的博客
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
url: "https://narozeol.github.io/"
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

include:
  - _pages

author:
  name   : "NaroZeol"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Student"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NaroZeol"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NaroZeol"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "目录"
      toc_icon: "cog"
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

enable_copy_code_button: true

# SEO
google_site_verification: ROW3yrTZIsYdNu5nbnbkHnphAttpGYEbffKwbBOgMNU
bing_site_verification: "E929E566B19B6994BF63D84A3A2FFF97"