#!/usr/bin/env bash
set -euo pipefail
umask 077
backup_dir=/home/naro/.local/share/naro-thoughts/backups
mkdir -p "$backup_dir"
python3 app.py backup "$backup_dir/thoughts-$(date -u +%Y%m%d-%H%M%S).sqlite"
# Only rotate backups generated by this script after today's backup succeeded.
find "$backup_dir" -maxdepth 1 -type f -name 'thoughts-????????-??????.sqlite' -mtime +30 -delete
